export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  images: string[]
  category: string
  season: string
  series: string
  description: string
  features: string[]
  specifications: {
    material: string
    fit: string
    care: string
    origin: string
  }
  variants: {
    colors: Array<{ name: string; value: string }>
    sizes: string[]
  }
  badges?: string[]
  inStock: boolean
  quantity: number
}

export const products: Product[] = [
  {
    id: "1",
    name: "GLITCH OVERSIZED TEE",
    price: 89,
    originalPrice: 120,
    image: "/black-glitch-tee.png",
    images: [
      "/black-glitch-tee.png",
      "/black-oversized-glitch-tee-back.png",
      "/black-oversized-glitch-tee-detail.png",
      "/black-glitch-tee-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 1",
    series: "NOISE",
    description:
      "Oversized streetwear tee featuring exclusive glitch graphics and premium cotton blend. Limited drop from our inaugural season.",
    features: [
      "Exclusive glitch graphic design",
      "Premium 280gsm cotton blend",
      "Oversized relaxed fit",
      "Screen-printed artwork",
      "Limited edition numbering",
    ],
    specifications: {
      material: "80% Cotton, 20% Polyester",
      fit: "Oversized",
      care: "Machine wash cold, hang dry",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited", "New"],
    inStock: true,
    quantity: 47,
  },
  {
    id: "2",
    name: "NEON DECAY LONGSLEEVE",
    price: 95,
    originalPrice: 120,
    image: "/dark-gray-decay-tee.png",
    images: [
      "/dark-gray-decay-tee.png",
      "/neon-decay-longsleeve-back.png",
      "/neon-decay-longsleeve-detail.png",
      "/neon-decay-longsleeve-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 1",
    series: "DECAY",
    description:
      "Long sleeve tee with neon decay graphics. Heavy cotton construction with distressed finishing touches.",
    features: [
      "Neon decay artwork",
      "Heavy 320gsm cotton",
      "Distressed hem details",
      "Reflective print elements",
      "Reinforced shoulders",
    ],
    specifications: {
      material: "100% Heavy Cotton",
      fit: "Regular",
      care: "Machine wash cold, tumble dry low",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited"],
    inStock: true,
    quantity: 23,
  },
  {
    id: "3",
    name: "STATIC CROP TEE",
    price: 75,
    image: "/black-cropped-static-tee.png",
    images: [
      "/black-cropped-static-tee.png",
      "/static-crop-tee-back.png",
      "/static-crop-tee-detail.png",
      "/static-crop-tee-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 1",
    series: "NOISE",
    description:
      "Cropped fit tee with all-over static noise pattern. Perfect for layering or standalone statement piece.",
    features: ["All-over static print", "Cropped silhouette", "Soft cotton blend", "Raw edge hem", "Unisex design"],
    specifications: {
      material: "90% Cotton, 10% Elastane",
      fit: "Cropped",
      care: "Hand wash recommended",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 31,
  },
  {
    id: "4",
    name: "CONCRETE BASIC TEE",
    price: 65,
    image: "/gray-concrete-tee.png",
    images: [
      "/gray-concrete-tee.png",
      "/concrete-basic-tee-back.png",
      "/concrete-basic-tee-detail.png",
      "/concrete-basic-tee-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Essential basic tee with subtle concrete texture. The foundation piece of any underground wardrobe.",
    features: ["Subtle texture print", "Classic fit", "Premium cotton", "Reinforced seams", "Minimal branding"],
    specifications: {
      material: "100% Organic Cotton",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Stone Beige", value: "#8a8a8a" },
        { name: "Void Black", value: "#000000" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    inStock: true,
    quantity: 89,
  },
  {
    id: "5",
    name: "NEON STRIKE TANK",
    price: 55,
    image: "/neon-strike-tank.png",
    images: [
      "/neon-strike-tank.png",
      "/neon-strike-tank-back.png",
      "/neon-strike-tank-detail.png",
      "/neon-strike-tank-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 2",
    series: "STRIKE",
    description: "Minimalist tank with bold neon strike graphics. Perfect for summer drops and layering pieces.",
    features: ["Bold neon graphics", "Lightweight fabric", "Athletic cut", "Moisture-wicking", "UV-resistant print"],
    specifications: {
      material: "95% Cotton, 5% Spandex",
      fit: "Athletic",
      care: "Machine wash cold, air dry",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 42,
  },
  {
    id: "6",
    name: "DECAY HOODIE",
    price: 145,
    originalPrice: 180,
    image: "/decay-hoodie.png",
    images: ["/decay-hoodie.png", "/decay-hoodie-back.png", "/decay-hoodie-detail.png", "/decay-hoodie-lifestyle.png"],
    category: "Apparel",
    season: "Season 2",
    series: "DECAY",
    description:
      "Premium oversized hoodie featuring decay graphics with orange accent details. Heavy construction for ultimate comfort.",
    features: [
      "Oversized fit",
      "Premium fleece lining",
      "Decay graphic artwork",
      "Kangaroo pocket",
      "Adjustable drawstrings",
    ],
    specifications: {
      material: "80% Cotton, 20% Polyester Fleece",
      fit: "Oversized",
      care: "Machine wash cold, tumble dry low",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited"],
    inStock: true,
    quantity: 18,
  },
  {
    id: "7",
    name: "VOID BOMBER JACKET",
    price: 195,
    originalPrice: 240,
    image: "/void-bomber-jacket.png",
    images: [
      "/void-bomber-jacket.png",
      "/void-bomber-jacket-back.png",
      "/void-bomber-jacket-detail.png",
      "/void-bomber-jacket-lifestyle.png",
    ],
    category: "Outerwear",
    season: "Season 2",
    series: "VOID",
    description:
      "Premium bomber jacket with void graphics and technical fabric construction. Perfect for urban exploration.",
    features: [
      "Water-resistant fabric",
      "Void graphic embroidery",
      "Ribbed cuffs and hem",
      "Multiple pockets",
      "Lightweight insulation",
    ],
    specifications: {
      material: "100% Nylon with DWR coating",
      fit: "Regular",
      care: "Dry clean only",
      origin: "Made in Italy",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited", "New"],
    inStock: true,
    quantity: 12,
  },
  {
    id: "8",
    name: "GLITCH CARGO PANTS",
    price: 125,
    image: "/glitch-cargo-pants.png",
    images: [
      "/glitch-cargo-pants.png",
      "/glitch-cargo-pants-side.png",
      "/glitch-cargo-pants-detail.png",
      "/glitch-cargo-pants-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 1",
    series: "NOISE",
    description: "Technical cargo pants with glitch pattern details and multiple utility pockets.",
    features: [
      "Multiple cargo pockets",
      "Adjustable waist",
      "Reinforced knees",
      "Glitch pattern details",
      "Tapered fit",
    ],
    specifications: {
      material: "65% Cotton, 35% Polyester Ripstop",
      fit: "Tapered",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Olive Drab", value: "#4a4a2a" },
      ],
      sizes: ["28", "30", "32", "34", "36", "38"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 34,
  },
  {
    id: "9",
    name: "NEON MESH TANK",
    price: 65,
    image: "/neon-mesh-tank.png",
    images: [
      "/neon-mesh-tank.png",
      "/neon-mesh-tank-back.png",
      "/neon-mesh-tank-detail.png",
      "/neon-mesh-tank-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 2",
    series: "STRIKE",
    description: "Lightweight mesh tank with neon strike graphics. Perfect for layering or summer wear.",
    features: ["Breathable mesh fabric", "Neon graphics", "Athletic cut", "Quick-dry material", "UV protection"],
    specifications: {
      material: "100% Polyester Mesh",
      fit: "Athletic",
      care: "Machine wash cold, air dry",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 56,
  },
  {
    id: "10",
    name: "CONCRETE SWEATSHIRT",
    price: 115,
    image: "/concrete-sweatshirt.png",
    images: [
      "/concrete-sweatshirt.png",
      "/concrete-sweatshirt-back.png",
      "/concrete-sweatshirt-detail.png",
      "/concrete-sweatshirt-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Essential crewneck sweatshirt with subtle concrete texture and minimal branding.",
    features: ["Concrete texture print", "Crewneck design", "Ribbed cuffs", "Premium fleece", "Minimal branding"],
    specifications: {
      material: "80% Cotton, 20% Polyester Fleece",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Stone Beige", value: "#8a8a8a" },
        { name: "Void Black", value: "#000000" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    inStock: true,
    quantity: 67,
  },
  {
    id: "11",
    name: "DECAY TRACK JACKET",
    price: 165,
    originalPrice: 200,
    image: "/decay-track-jacket.png",
    images: [
      "/decay-track-jacket.png",
      "/decay-track-jacket-back.png",
      "/decay-track-jacket-detail.png",
      "/decay-track-jacket-lifestyle.png",
    ],
    category: "Outerwear",
    season: "Season 1",
    series: "DECAY",
    description: "Retro-inspired track jacket with decay graphics and contrast piping details.",
    features: ["Full zip closure", "Contrast piping", "Decay graphics", "Side pockets", "Elastic cuffs"],
    specifications: {
      material: "100% Polyester Tricot",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited"],
    inStock: true,
    quantity: 29,
  },
  {
    id: "12",
    name: "STATIC SHORTS",
    price: 85,
    image: "/static-shorts.png",
    images: [
      "/static-shorts.png",
      "/static-shorts-back.png",
      "/static-shorts-detail.png",
      "/static-shorts-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 1",
    series: "NOISE",
    description: "Comfortable shorts with all-over static pattern and adjustable waistband.",
    features: ["All-over static print", "Elastic waistband", "Side pockets", "Mesh lining", "Quick-dry fabric"],
    specifications: {
      material: "90% Polyester, 10% Spandex",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 43,
  },
  {
    id: "13",
    name: "VOID BEANIE",
    price: 35,
    image: "/void-beanie.png",
    images: ["/void-beanie.png", "/void-beanie-side.png", "/void-beanie-detail.png", "/void-beanie-lifestyle.png"],
    category: "Accessories",
    season: "Season 2",
    series: "VOID",
    description: "Minimalist beanie with embroidered void logo. Essential winter accessory.",
    features: ["Embroidered logo", "Ribbed knit", "Cuffed design", "One size fits all", "Soft acrylic blend"],
    specifications: {
      material: "100% Acrylic",
      fit: "One Size",
      care: "Hand wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 78,
  },
  {
    id: "14",
    name: "GLITCH CAP",
    price: 45,
    image: "/glitch-cap.png",
    images: ["/glitch-cap.png", "/glitch-cap-side.png", "/glitch-cap-detail.png", "/glitch-cap-lifestyle.png"],
    category: "Accessories",
    season: "Season 1",
    series: "NOISE",
    description: "Six-panel cap with embroidered glitch logo and adjustable strap.",
    features: ["Embroidered logo", "Adjustable strap", "Curved visor", "Six-panel construction", "Cotton twill"],
    specifications: {
      material: "100% Cotton Twill",
      fit: "Adjustable",
      care: "Spot clean only",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 92,
  },
  {
    id: "15",
    name: "NEON WINDBREAKER",
    price: 135,
    image: "/neon-windbreaker.png",
    images: [
      "/neon-windbreaker.png",
      "/neon-windbreaker-back.png",
      "/neon-windbreaker-detail.png",
      "/neon-windbreaker-lifestyle.png",
    ],
    category: "Outerwear",
    season: "Season 2",
    series: "STRIKE",
    description: "Lightweight windbreaker with neon strike graphics and packable design.",
    features: ["Packable design", "Water-resistant", "Neon graphics", "Elastic cuffs", "Mesh lining"],
    specifications: {
      material: "100% Nylon Ripstop",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 38,
  },
  {
    id: "16",
    name: "CONCRETE JOGGERS",
    price: 95,
    image: "/concrete-joggers.png",
    images: [
      "/concrete-joggers.png",
      "/concrete-joggers-side.png",
      "/concrete-joggers-detail.png",
      "/concrete-joggers-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Comfortable joggers with concrete texture details and tapered fit.",
    features: ["Concrete texture print", "Elastic waistband", "Tapered fit", "Side pockets", "Ribbed cuffs"],
    specifications: {
      material: "80% Cotton, 20% Polyester",
      fit: "Tapered",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
        { name: "Stone Beige", value: "#8a8a8a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    inStock: true,
    quantity: 54,
  },
  {
    id: "17",
    name: "DECAY POLO",
    price: 75,
    image: "/decay-polo.png",
    images: ["/decay-polo.png", "/decay-polo-back.png", "/decay-polo-detail.png", "/decay-polo-lifestyle.png"],
    category: "Apparel",
    season: "Season 1",
    series: "DECAY",
    description: "Classic polo shirt with decay graphics and premium pique cotton construction.",
    features: ["Pique cotton", "Three-button placket", "Decay graphics", "Ribbed collar", "Side vents"],
    specifications: {
      material: "100% Pique Cotton",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 61,
  },
  {
    id: "18",
    name: "VOID TOTE BAG",
    price: 55,
    image: "/void-tote-bag.png",
    images: [
      "/void-tote-bag.png",
      "/void-tote-bag-side.png",
      "/void-tote-bag-detail.png",
      "/void-tote-bag-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "VOID",
    description: "Minimalist tote bag with void logo and heavy canvas construction.",
    features: ["Heavy canvas", "Reinforced handles", "Interior pocket", "Void logo print", "Large capacity"],
    specifications: {
      material: "100% Heavy Canvas",
      fit: "One Size",
      care: "Spot clean only",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 87,
  },
  {
    id: "19",
    name: "GLITCH SOCKS",
    price: 25,
    image: "/glitch-socks.png",
    images: ["/glitch-socks.png", "/glitch-socks-pair.png", "/glitch-socks-detail.png", "/glitch-socks-lifestyle.png"],
    category: "Accessories",
    season: "Season 1",
    series: "NOISE",
    description: "Crew socks with glitch pattern and cushioned sole for comfort.",
    features: ["Glitch pattern", "Cushioned sole", "Reinforced heel", "Moisture-wicking", "Crew height"],
    specifications: {
      material: "80% Cotton, 15% Polyester, 5% Elastane",
      fit: "One Size",
      care: "Machine wash warm",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 156,
  },
  {
    id: "20",
    name: "NEON BUCKET HAT",
    price: 55,
    image: "/neon-bucket-hat.png",
    images: [
      "/neon-bucket-hat.png",
      "/neon-bucket-hat-side.png",
      "/neon-bucket-hat-detail.png",
      "/neon-bucket-hat-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "STRIKE",
    description: "Bucket hat with neon strike graphics and UV protection.",
    features: ["UV protection", "Neon graphics", "Packable design", "Adjustable chin strap", "Cotton twill"],
    specifications: {
      material: "100% Cotton Twill",
      fit: "One Size",
      care: "Spot clean only",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 73,
  },
  {
    id: "21",
    name: "CONCRETE VEST",
    price: 105,
    image: "/concrete-vest.png",
    images: [
      "/concrete-vest.png",
      "/concrete-vest-back.png",
      "/concrete-vest-detail.png",
      "/concrete-vest-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Utility vest with concrete texture and multiple pockets for urban exploration.",
    features: ["Multiple pockets", "Concrete texture", "Zip closure", "Adjustable sides", "Lightweight"],
    specifications: {
      material: "100% Nylon Ripstop",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
        { name: "Olive Drab", value: "#4a4a2a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    inStock: true,
    quantity: 41,
  },
  {
    id: "22",
    name: "DECAY BANDANA",
    price: 30,
    image: "/decay-bandana.png",
    images: [
      "/decay-bandana.png",
      "/decay-bandana-folded.png",
      "/decay-bandana-detail.png",
      "/decay-bandana-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 1",
    series: "DECAY",
    description: "Classic bandana with decay pattern and premium cotton construction.",
    features: ["Decay pattern", "Premium cotton", "Versatile styling", "Hand-rolled edges", "Square cut"],
    specifications: {
      material: "100% Cotton",
      fit: "One Size",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 94,
  },
  {
    id: "23",
    name: "VOID BACKPACK",
    price: 185,
    originalPrice: 220,
    image: "/void-backpack.png",
    images: [
      "/void-backpack.png",
      "/void-backpack-side.png",
      "/void-backpack-detail.png",
      "/void-backpack-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "VOID",
    description: "Technical backpack with void graphics and laptop compartment for urban commuting.",
    features: ["Laptop compartment", "Water-resistant", "Void graphics", "Padded straps", "Multiple compartments"],
    specifications: {
      material: "100% Nylon with PU coating",
      fit: "One Size",
      care: "Spot clean only",
      origin: "Made in Italy",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["Limited"],
    inStock: true,
    quantity: 23,
  },
  {
    id: "24",
    name: "GLITCH BELT",
    price: 65,
    image: "/glitch-belt.png",
    images: ["/glitch-belt.png", "/glitch-belt-buckle.png", "/glitch-belt-detail.png", "/glitch-belt-lifestyle.png"],
    category: "Accessories",
    season: "Season 1",
    series: "NOISE",
    description: "Canvas belt with glitch logo buckle and adjustable length.",
    features: ["Canvas construction", "Metal buckle", "Glitch logo", "Adjustable length", "D-ring detail"],
    specifications: {
      material: "100% Canvas with Metal Hardware",
      fit: "Adjustable",
      care: "Spot clean only",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["S/M", "L/XL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 68,
  },
  {
    id: "25",
    name: "NEON FACE MASK",
    price: 20,
    image: "/neon-face-mask.png",
    images: [
      "/neon-face-mask.png",
      "/neon-face-mask-side.png",
      "/neon-face-mask-detail.png",
      "/neon-face-mask-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "STRIKE",
    description: "Reusable face mask with neon strike graphics and comfortable fit.",
    features: ["Reusable design", "Neon graphics", "Adjustable ear loops", "Breathable fabric", "Machine washable"],
    specifications: {
      material: "95% Cotton, 5% Spandex",
      fit: "One Size",
      care: "Machine wash hot",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 234,
  },
  {
    id: "31",
    name: "STATIC DENIM JACKET",
    price: 175,
    originalPrice: 210,
    image: "/static-denim-jacket.png",
    images: [
      "/static-denim-jacket.png",
      "/static-denim-jacket-back.png",
      "/static-denim-jacket-detail.png",
      "/static-denim-jacket-lifestyle.png",
    ],
    category: "Outerwear",
    season: "Season 1",
    series: "NOISE",
    description: "Premium denim jacket with static noise pattern and distressed finishing.",
    features: [
      "Static noise pattern",
      "Distressed details",
      "Classic denim construction",
      "Chest pockets",
      "Adjustable cuffs",
    ],
    specifications: {
      material: "100% Cotton Denim",
      fit: "Regular",
      care: "Machine wash cold, hang dry",
      origin: "Made in Turkey",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Indigo Blue", value: "#1e3a8a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited", "New"],
    inStock: true,
    quantity: 28,
  },
  {
    id: "41",
    name: "URBAN DECAY HOODIE",
    price: 155,
    originalPrice: 185,
    image: "/urban-decay-hoodie.png",
    images: [
      "/urban-decay-hoodie.png",
      "/urban-decay-hoodie-back.png",
      "/urban-decay-hoodie-detail.png",
      "/urban-decay-hoodie-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 3",
    series: "DECAY",
    description: "Heavy-weight hoodie with urban decay graphics and premium fleece construction.",
    features: ["Urban decay artwork", "Premium fleece lining", "Oversized fit", "Kangaroo pocket", "Reinforced seams"],
    specifications: {
      material: "85% Cotton, 15% Polyester Fleece",
      fit: "Oversized",
      care: "Machine wash cold, tumble dry low",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Rust Red", value: "#8b4513" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["Limited", "New"],
    inStock: true,
    quantity: 32,
  },
  {
    id: "42",
    name: "GLITCH TECH PANTS",
    price: 135,
    image: "/glitch-tech-pants.png",
    images: [
      "/glitch-tech-pants.png",
      "/glitch-tech-pants-back.png",
      "/glitch-tech-pants-detail.png",
      "/glitch-tech-pants-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 1",
    series: "NOISE",
    description: "Technical pants with glitch pattern and water-resistant coating for urban exploration.",
    features: [
      "Water-resistant coating",
      "Glitch pattern details",
      "Multiple zip pockets",
      "Articulated knees",
      "Adjustable cuffs",
    ],
    specifications: {
      material: "70% Nylon, 30% Polyester with DWR coating",
      fit: "Tapered",
      care: "Machine wash cold, hang dry",
      origin: "Made in Italy",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["28", "30", "32", "34", "36", "38"],
    },
    badges: ["New", "Technical"],
    inStock: true,
    quantity: 26,
  },
  {
    id: "33",
    name: "DECAY FLANNEL SHIRT",
    price: 95,
    image: "/decay-flannel-shirt.png",
    images: [
      "/decay-flannel-shirt.png",
      "/decay-flannel-shirt-back.png",
      "/decay-flannel-shirt-detail.png",
      "/decay-flannel-shirt-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 1",
    series: "DECAY",
    description: "Soft flannel shirt with decay pattern and vintage wash finish.",
    features: [
      "Decay pattern print",
      "Vintage wash finish",
      "Button-up closure",
      "Chest pockets",
      "Soft flannel fabric",
    ],
    specifications: {
      material: "100% Cotton Flannel",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
        { name: "Rust Red", value: "#8b4513" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 44,
  },
  {
    id: "34",
    name: "NEON MESH SHORTS",
    price: 65,
    image: "/neon-mesh-shorts.png",
    images: [
      "/neon-mesh-shorts.png",
      "/neon-mesh-shorts-back.png",
      "/neon-mesh-shorts-detail.png",
      "/neon-mesh-shorts-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 2",
    series: "STRIKE",
    description: "Athletic mesh shorts with neon strike graphics and moisture-wicking fabric.",
    features: [
      "Moisture-wicking mesh",
      "Neon strike graphics",
      "Elastic waistband",
      "Side pockets",
      "Quick-dry technology",
    ],
    specifications: {
      material: "100% Polyester Mesh",
      fit: "Athletic",
      care: "Machine wash cold, air dry",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
        { name: "Neon Green", value: "#39ff14" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 67,
  },
  {
    id: "35",
    name: "CONCRETE WORK PANTS",
    price: 115,
    image: "/concrete-work-pants.png",
    images: [
      "/concrete-work-pants.png",
      "/concrete-work-pants-back.png",
      "/concrete-work-pants-detail.png",
      "/concrete-work-pants-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Durable work pants with concrete texture and reinforced construction.",
    features: [
      "Concrete texture pattern",
      "Reinforced knees",
      "Tool pockets",
      "Heavy-duty construction",
      "Straight leg fit",
    ],
    specifications: {
      material: "65% Cotton, 35% Polyester Canvas",
      fit: "Straight",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
        { name: "Olive Drab", value: "#4a4a2a" },
      ],
      sizes: ["30", "32", "34", "36", "38", "40"],
    },
    inStock: true,
    quantity: 39,
  },
  {
    id: "36",
    name: "GLITCH CHAIN NECKLACE",
    price: 85,
    image: "/glitch-chain-necklace.png",
    images: [
      "/glitch-chain-necklace.png",
      "/glitch-chain-necklace-detail.png",
      "/glitch-chain-necklace-pendant.png",
      "/glitch-chain-necklace-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 1",
    series: "NOISE",
    description: "Stainless steel chain necklace with glitch logo pendant.",
    features: [
      "Stainless steel construction",
      "Glitch logo pendant",
      "Adjustable length",
      "Hypoallergenic",
      "Tarnish resistant",
    ],
    specifications: {
      material: "316L Stainless Steel",
      fit: "Adjustable",
      care: "Wipe clean with soft cloth",
      origin: "Made in Italy",
    },
    variants: {
      colors: [
        { name: "Silver", value: "#c0c0c0" },
        { name: "Black Steel", value: "#2c2c2c" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New", "Premium"],
    inStock: true,
    quantity: 56,
  },
  {
    id: "37",
    name: "VOID CROSSBODY BAG",
    price: 125,
    image: "/void-crossbody-bag.png",
    images: [
      "/void-crossbody-bag.png",
      "/void-crossbody-bag-side.png",
      "/void-crossbody-bag-detail.png",
      "/void-crossbody-bag-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "VOID",
    description: "Compact crossbody bag with void graphics and water-resistant coating.",
    features: ["Water-resistant coating", "Void graphics", "Adjustable strap", "Multiple compartments", "YKK zippers"],
    specifications: {
      material: "100% Nylon with PU coating",
      fit: "One Size",
      care: "Spot clean only",
      origin: "Made in Vietnam",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Concrete Gray", value: "#2a2a2a" },
      ],
      sizes: ["One Size"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 48,
  },
  {
    id: "38",
    name: "DECAY THERMAL SHIRT",
    price: 75,
    image: "/decay-thermal-shirt.png",
    images: [
      "/decay-thermal-shirt.png",
      "/decay-thermal-shirt-back.png",
      "/decay-thermal-shirt-detail.png",
      "/decay-thermal-shirt-lifestyle.png",
    ],
    category: "Apparel",
    season: "Season 1",
    series: "DECAY",
    description: "Thermal long sleeve shirt with decay graphics and waffle knit construction.",
    features: ["Waffle knit construction", "Decay graphics", "Thermal properties", "Crew neck design", "Ribbed cuffs"],
    specifications: {
      material: "60% Cotton, 40% Polyester Thermal",
      fit: "Regular",
      care: "Machine wash cold",
      origin: "Made in Portugal",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
        { name: "Stone Beige", value: "#8a8a8a" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    inStock: true,
    quantity: 62,
  },
  {
    id: "39",
    name: "NEON RUNNING SHORTS",
    price: 55,
    image: "/neon-running-shorts.png",
    images: [
      "/neon-running-shorts.png",
      "/neon-running-shorts-back.png",
      "/neon-running-shorts-detail.png",
      "/neon-running-shorts-lifestyle.png",
    ],
    category: "Bottoms",
    season: "Season 2",
    series: "STRIKE",
    description: "Performance running shorts with neon strike graphics and built-in liner.",
    features: [
      "Built-in liner",
      "Neon strike graphics",
      "Moisture-wicking fabric",
      "Reflective details",
      "Side split hem",
    ],
    specifications: {
      material: "88% Polyester, 12% Spandex",
      fit: "Athletic",
      care: "Machine wash cold, air dry",
      origin: "Made in Vietnam",
    },
    variants: {
      colors: [
        { name: "Void Black", value: "#000000" },
        { name: "Static White", value: "#ffffff" },
        { name: "Neon Orange", value: "#ff6600" },
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    badges: ["New", "Performance"],
    inStock: true,
    quantity: 73,
  },
  {
    id: "40",
    name: "CONCRETE PHONE CASE",
    price: 35,
    image: "/concrete-phone-case.png",
    images: [
      "/concrete-phone-case.png",
      "/concrete-phone-case-back.png",
      "/concrete-phone-case-detail.png",
      "/concrete-phone-case-lifestyle.png",
    ],
    category: "Accessories",
    season: "Season 2",
    series: "FOUNDATION",
    description: "Protective phone case with concrete texture and shock-absorbing design.",
    features: [
      "Concrete texture pattern",
      "Shock-absorbing design",
      "Raised edges protection",
      "Wireless charging compatible",
      "Precise cutouts",
    ],
    specifications: {
      material: "TPU with Textured Finish",
      fit: "iPhone/Samsung Models",
      care: "Wipe clean",
      origin: "Made in China",
    },
    variants: {
      colors: [
        { name: "Concrete Gray", value: "#2a2a2a" },
        { name: "Void Black", value: "#000000" },
      ],
      sizes: ["iPhone 14/15", "Samsung S23/S24"],
    },
    badges: ["New"],
    inStock: true,
    quantity: 124,
  },
]

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((product) => product.category === category)
}

export const getProductsBySeason = (season: string): Product[] => {
  return products.filter((product) => product.season === season)
}

export const getProductsBySeries = (series: string): Product[] => {
  return products.filter((product) => product.series === series)
}
